### ISSUE TITLE
Error Capture Page Screenshot' could not be run on failure 

### ISSUE THREAD

**Issue by cdasadiya** [brain-tec/odoo-robot-framework#54] opened 2017-04-03 09:52 UTC
[ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: Multiple keywords with name **'Capture Page Screenshot'** found. Give the full name of the keyword you want to use:
    **AppiumLibrary.Capture Page Screenshot
    Selenium2Library.Capture Page Screenshot**
I have got the issue while run the pybot demo_8_0_full_workflow.robot for odoo automation test case purpose

**Comment by ghost** [comment] 2017-04-03 10:25
We are not using Appium, so I have never had this problem, but I guess it can be solved changing the way to import Selenium2Library to your robot file tests. 

Selenium2Library is configured by default to Capture a page screenshot when a selenium2library keyword fails. You can change it or probably better you can specify which keyword you want to use.
If you want to avoid selenium2library to capture screenshot when it fails, use:
`Library     |   Selenium2Library  |  run_on_failure=Nothing`
If you prefer to use the selenium2library to take screenshot on failure you can use:
`Library     |   Selenium2Library  |  run_on_failure=Selenium2Library.Capture Page Screenshot`

I hope it helps, and please let me know if it solves your problem.

**Comment by cdasadiya** [comment] 2017-04-03 11:24
Yup that one is fixed from my side but I got the **No keyword with name 'Execute Javascript' found.**
Can we elaborate more with this issue because Is it part of firefox plugins configuration or not ?

**options-1 :  Library | Selenium2Library | run_on_failure=Selenium2Library.Capture Page Screenshot**
**Error Raise :** 

[ ERROR ] Error in file '/home/user1/Music/RB_AUTO_TEST/odoo-robot-framework/odoo_8_0.robot': Non-existing setting 'Library | Selenium2Library | run_on_failure=Selenium2Library.Capture Page Screenshot'.

**option-2 : Library | Selenium2Library | run_on_failure=Nothing**

Error Raise 
[ ERROR ] Error in file '/home/user1/Music/RB_AUTO_TEST/odoo-robot-framework/odoo_8_0.robot': Non-existing setting 'Library | Selenium2Library | run_on_failure=Nothing'.

**Comment by ghost** [comment] 2017-04-03 12:40
Hi, in this case | means tabulation. So it should be:
`Library     Selenium2Library      run_on_failure=run_on_failure=Selenium2Library.Capture Page Screenshot`
with tabulations instead of | that I wrote in the previous comment. 

That should fix both problems. Probably the Execute Javascript is becuase you need to import Selenium2library to use the Execute Javascript keyword

**Comment by cdasadiya74** [comment] 2017-04-05 05:19
Again the same error

**Comment by cdasadiya** [comment] 2017-04-05 05:28
Again got the same error 

[ ERROR ] Error in file '/home/user1/Music/RB_AUTO_TEST/odoo-robot-framework/odoo_8_0.robot': Non-existing setting 'Library Selenium2Library run_on_failure=run_on_failure=Selenium2Library.Capture Page Screenshot
Is there any other option for solve our error ?
Why should we need to write the run_on_failure option with our robot file.?

**Comment by ghost** [comment] 2017-04-05 06:59
The problem is a incompatibility between 2 keywords, one from Selenium2Library and the other from AppiumLibrary. They have the same name and robot does not know which one do you want to execute. Selenium2library is configured by default to call Capture Page Screenshot when a test fails, but the system cant decide which one.
Reading your error, It seems to be a problem with the tabulation or spaces. You can also write 4 or more spaces instead of tabulations. Apparently you wrote not enough spaces, and maybe you also wrote twice the "run_on_failure".
`Library.........Selenium2Library.........run_on_failure=Selenium2Library.Capture Page Screenshot`
(don't forget to replace dots for spaces, at least 4)

The other option is to not import Appium, but I guess you need it to test in phones or tablets, so we can discard this option.

You can also have a look into http://robotframework.org/Selenium2Library/Selenium2Library.html, maybe it can help you more.

**Comment by cdasadiya** [comment] 2017-04-05 08:46
**Robot Automation test cases for the Robot Framework for Odoo Version 8** 

**My odoo_8_0.robot**

*** Settings ***

Documentation  Common keywords for OpenERP tests
...            versions of the application. The correct SUT specific resource
...            is imported based on ${SUT} variable. SeleniumLibrary is also
...            imported here so that no other file needs to import it.

Library     String
Library     XvfbRobot
Library.........Selenium2Library.........run_on_failure=Selenium2Library.Capture Page Screenshot


*** Keywords ***
Set Up
    Set Global Variable     ${v8_robot_test}     http://${localhost}:${8069}

    #ff default caps shoul be always present
    ${ff default caps}=         Evaluate    sys.modules['selenium.webdriver'].common.desired_capabilities.DesiredCapabilities.FIREFOX    sys,selenium.webdriver
    #marionette optional, just if we need it
    Set To Dictionary     ${ff default caps}    marionette=${True}

    #Virtual display if we want the test to run in background
    Start Virtual Display   1920    1080

# checked: 8.0 ok
Login    [Arguments]    ${user}=demo    ${password}=demo    ${db}=v8_robot_test
    Set Global Variable     ${http://localhost:8069/web/login?redirect=http%3A%2F%2Flocalhost%3A8069%2Fweb%3F}     http://127.0.0.1:8069

# checked: 8.0 ok
DatabaseConnect    [Arguments]    ${odoo_db}=${v8_robot_test}    ${odoo_db_user}=${admin}    ${odoo_db_password}=${a}    ${odoo_db_server}=${http://localhost:8069/web/login?redirect=http%3A%2F%2Flocalhost%3A8069%2Fweb%3F}    ${odoo_db_port}=${8069}
		Connect To Database Using Custom Params	psycopg2        database='${v8_robot_test}',user='${admin}',password='${a}',host='${htt://localhost}',port=${8069}

# checked: 8.0 ok
DatabaseDisconnect
		Disconnect from Database

SubMenuXMLid    [Arguments]		${Name}
	${MODULE}=              Fetch From Left            ${Name}              .
    ${NAME}=                Fetch From Right           ${Name}              .
    ${SubMenuID}=		    get_menu_res_id	${ODOO_URL_DB}	${ODOO_DB}	${USER}	${PASSWORD}	${MODULE}	${NAME}
    Run Keyword If          ${SubMenuID}               SubMenu         ${SubMenuID}
    Run Keyword Unless          ${SubMenuID}        Fail    ERROR: Module or Name not correct
   
MainMenuXMLid    [Arguments]    ${Name}
	${MODULE}=              Fetch From Left            ${Name}              .
    ${NAME}=                Fetch From Right           ${Name}              .
    ${MainMenuID}=		    get_menu_res_id	${ODOO_URL_DB}	${ODOO_DB}	${USER}	${PASSWORD}	${MODULE}	${NAME}
    Run Keyword If          ${MainMenuID}               MainMenu         ${MainMenuID}
    Run Keyword Unless          ${MainMenuID}       Fail    ERROR: Module or Name not correct


# checked: 8.0 ok
ChangeView    [Arguments]    ${view}
   Click Link                          xpath=//div[contains(@class,'openerp')][last()]//ul[contains(@class,'oe_view_manager_switch')]//a[contains(@data-view-type,'${view}')]
   ElementPostCheck

# main window
# view-manager-main-content

# Checks that are done always before a element is executed
ElementPreCheck    [Arguments]    ${element}
	Execute Javascript      console.log("${element}");
	# Element may be in a tab. So click the parent tab. If there is no parent tab, forget about the result
    Execute Javascript      var path="${element}".replace('xpath=','');var id=document.evaluate("("+path+")/ancestor::div[contains(@class,'oe_notebook_page')]/@id",document,null,XPathResult.STRING_TYPE,null).stringValue; if(id != ''){ window.location = "#"+id; $("a[href='#"+id+"']").click(); console.log("Clicked at #" + id); } return true;


ElementPostCheck
   # Check that page is not blocked by RPC Call
#   Wait Until Page Contains Element	xpath=//div[contains(@class,'openerp_webclient_container') and not(contains(@class, 'oe_wait'))]


WriteInField                [Arguments]     ${model}    ${fieldname}    ${value}
    ElementPreCheck         xpath=//div[contains(@class,'openerp')][last()]//input[@data-bt-testing-model_name='${model}' and @data-bt-testing-name='${fieldname}']|textarea[@data-bt-testing-model_name='${model}' and @data-bt-testing-name='${fieldname}']
    Input Text              xpath=//div[contains(@class,'openerp')][last()]//input[@data-bt-testing-model_name='${model}' and @data-bt-testing-name='${fieldname}']|textarea[@data-bt-testing-model_name='${model}' and @data-bt-testing-name='${fieldname}']    ${value}

# checked: 8.0 ok
Many2OneSelect    [Arguments]    ${model}    ${field}    ${value}
    ElementPreCheck	    xpath=//div[contains(@class,'openerp')][last()]//input[@data-bt-testing-model_name='${model}' and @data-bt-testing-name='${field}']
    Input Text		    xpath=//div[contains(@class,'openerp')][last()]//input[@data-bt-testing-model_name='${model}' and @data-bt-testing-name='${field}']    ${value}
    Click Link             xpath=//ul[contains(@class,'ui-autocomplete') and not(contains(@style,'display: none'))]/li[1]/a
    Textfield Should Contain    xpath=//div[contains(@class,'openerp')][last()]//input[@data-bt-testing-model_name='${model}' and @data-bt-testing-name='${field}']    ${value}
    ElementPostCheck

X2Many-Many2OneSelect    [Arguments]    ${model}    ${field}    ${value}
    Input Text		    xpath=//div[contains(@class,'openerp')][last()]//input[@data-bt-testing-model_name='${model}' and @data-bt-testing-name='${field}']    ${value}
    Click Link             xpath=//ul[contains(@class,'ui-autocomplete') and not(contains(@style,'display: none'))]/li[1]/a
    Textfield Should Contain    xpath=//div[contains(@class,'openerp')][last()]//input[@data-bt-testing-model_name='${model}' and @data-bt-testing-name='${field}']    ${value}
    ElementPostCheck

Date    [Arguments]    ${model}    ${field}    ${value}
    Click Element        xpath=//div[contains(@class,'openerp')][last()]//img[ancestor::span[descendant::input[@data-bt-testing-model_name='${model}' and @data-bt-testing-name='${field}']] and @class="oe_input_icon oe_datepicker_trigger"]
    sleep   1s
    Click Element        xpath=//div[contains(@class,'openerp')][last()]//input[@data-bt-testing-model_name='${model}' and @data-bt-testing-name='${field}']
    Input Text           xpath=//div[contains(@class,'openerp')][last()]//input[@data-bt-testing-model_name='${model}' and @data-bt-testing-name='${field}']    ${value}
    ElementPostCheck

Char    [Arguments]    ${model}    ${field}    ${value}
    ElementPreCheck        xpath=//div[contains(@class,'openerp')][last()]//input[@data-bt-testing-model_name='${model}' and @data-bt-testing-name='${field}']
    Execute Javascript     $("div.openerp:last input[data-bt-testing-model_name='${model}'][data-bt-testing-name='${field}']").val(''); return true;
    Input Text             xpath=//div[contains(@class,'openerp')][last()]//input[@data-bt-testing-model_name='${model}' and @data-bt-testing-name='${field}']    ${value}
    ElementPostCheck

Float    [Arguments]    ${model}    ${field}    ${value}
    ElementPreCheck        xpath=//div[contains(@class,'openerp')][last()]//input[@data-bt-testing-model_name='${model}' and @data-bt-testing-name='${field}']
    Input Text             xpath=//div[contains(@class,'openerp')][last()]//input[@data-bt-testing-model_name='${model}' and @data-bt-testing-name='${field}']    ${value}
    ElementPostCheck

Text    [Arguments]    ${model}    ${field}    ${value}
    ElementPreCheck        xpath=//div[contains(@class,'openerp')][last()]//textarea[@data-bt-testing-model_name='${model}' and @data-bt-testing-name='${field}']
    Input Text             xpath=//div[contains(@class,'openerp')][last()]//textarea[@data-bt-testing-model_name='${model}' and @data-bt-testing-name='${field}']    ${value}
    ElementPostCheck

Select-Option    [Arguments]    ${model}    ${field}    ${value}    
    ElementPreCheck        xpath=//div[contains(@class,'openerp')][last()]//select[@data-bt-testing-model_name='${model}' and @data-bt-testing-name='${field}']
    #Select From List	xpath=//div[contains(@class,'openerp')][last()]//select[@data-bt-testing-model_name='${model}' and @data-bt-testing-name='${field}']    ${value}
    click element       xpath=//div[contains(@class,'openerp')][last()]//select[@data-bt-testing-model_name='${model}' and @data-bt-testing-name='${field}']
    click element       xpath=//div[contains(@class,'openerp')][last()]//select[@data-bt-testing-model_name='${model}' and @data-bt-testing-name='${field}']/option[@data-bt-testing-value='${value}']
    ElementPostCheck

Checkbox-Select    [Arguments]    ${model}    ${field}
    ElementPreCheck        xpath=//div[contains(@class,'openerp')][last()]//input[@type='checkbox' and @data-bt-testing-name='${field}']
    #Checkbox Should Not Be Selected	xpath=//div[contains(@class,'openerp')][last()]//input[@type='checkbox' and @data-bt-testing-name='${field}']
    Click Element          xpath=//div[contains(@class,'openerp')][last()]//input[@type='checkbox' and @data-bt-testing-name='${field}']
    ElementPostCheck

NotebookPage    [Arguments]    ${model}=None
    Wait For Condition      return true;

# checked: 8.0 ok
NewOne2Many    [Arguments]    ${model}    ${field}
    ElementPreCheck        xpath=//div[contains(@class,'openerp')][last()]//div[contains(@class,'oe_form_field_one2many')]/div[@data-bt-testing-model_name='${model}' and @data-bt-testing-name='${field}']//tr/td[contains(@class,'oe_form_field_one2many_list_row_add')]/a
    Click Link             xpath=(//div[contains(@class,'openerp')][last()]//div[contains(@class,'oe_form_field_one2many')]/div[@data-bt-testing-model_name='${model}' and @data-bt-testing-name='${field}']//tr/td[contains(@class,'oe_form_field_one2many_list_row_add')]/a)[last()]
    ElementPostCheck

One2ManySelectRecord  [Arguments]    ${model}    ${field}    ${submodel}    @{fields}
    ElementPreCheck    xpath=//div[@data-bt-testing-model_name='${model}' and @data-bt-testing-name='${field}']

    # Initialize variable
    ${pre_check_xpath}=    Set Variable
    ${post_check_xpath}=    Set Variable
    ${pre_click_xpath}=    Set Variable
    ${post_click_xpath}=    Set Variable
    ${pre_check_xpath}=    Catenate    (//div[@data-bt-testing-model_name='${model}' and @data-bt-testing-name='${field}']//table[contains(@class,'oe_list_content')]//tr[descendant::td[
    ${post_check_xpath}=    Catenate    ]])[1]
    ${pre_click_xpath}=    Catenate    (//div[@data-bt-testing-model_name='${model}' and @data-bt-testing-name='${field}']//table[contains(@class,'oe_list_content')]//tr[
    ${post_click_xpath}=    Catenate    ]/td)[1]
    ${xpath}=    Set Variable

    # Got throught all field=value and to select the correct record
    : FOR    ${field}    IN  @{fields}
    # Split the string in fieldname=fieldvalue
    \    ${fieldname}    ${fieldvalue}=    Split String    ${field}    separator==    max_split=1
    \    ${fieldxpath}=    Catenate    @data-bt-testing-model_name='${submodel}' and @data-field='${fieldname}'

         # We first check if this field is in the view and visible
         # otherwise a single field can break the whole command

    \    ${checkxpath}=     Catenate    ${pre_check_xpath} ${fieldxpath} ${post_check_xpath}
    \    Log To Console    ${checkxpath}
    \    ${status}    ${value}=    Run Keyword And Ignore Error    Page Should Contain Element    xpath=${checkxpath}

         # In case the field is not there, log a error
    \    Run Keyword Unless     '${status}' == 'PASS'    Log    Field ${fieldname} not in the view or unvisible
         # In case the field is there, add the path to the xpath
    \    ${xpath}=    Set Variable If    '${status}' == 'PASS'    ${xpath} and descendant::td[${fieldxpath} and string()='${fieldvalue}']    ${xpath}

    # remove first " and " again (5 characters)
    ${xpath}=   Get Substring    ${xpath}    5
    ${xpath}=    Catenate    ${pre_click_xpath}    ${xpath}    ${post_click_xpath}
    Click Element    xpath=${xpath}
    ElementPostCheck


SelectListView  [Arguments]    ${model}    @{fields}
    # Initialize variable
    ${xpath}=    Set Variable

    # Got throught all field=value and to select the correct record
    : FOR    ${field}    IN  @{fields}
    # Split the string in fieldname=fieldvalue
    \    ${fieldname}    ${fieldvalue}=    Split String    ${field}    separator==    max_split=1
    \    ${fieldxpath}=    Catenate    @data-bt-testing-model_name='${model}' and @data-field='${fieldname}'

         # We first check if this field is in the view and visible
         # otherwise a single field can break the whole command

    \    ${checkxpath}=     Catenate    (//table[contains(@class,'oe_list_content')]//tr[descendant::td[${fieldxpath}]])[1]
    \    ${status}    ${value}=    Run Keyword And Ignore Error    Page Should Contain Element    xpath=${checkxpath}

         # In case the field is not there, log a error
    \    Run Keyword Unless     '${status}' == 'PASS'    Log    Field ${fieldname} not in the view or unvisible
         # In case the field is there, add the path to the xpath
    \    ${xpath}=    Set Variable If    '${status}' == 'PASS'    ${xpath} and descendant::td[${fieldxpath} and string()='${fieldvalue}']    ${xpath}

    # remove first " and " again (5 characters)
    ${xpath}=   Get Substring    ${xpath}    5
    ${xpath}=    Catenate    (//table[contains(@class,'oe_list_content')]//tr[${xpath}]/td)[1]
    Click Element    xpath=${xpath}
    ElementPostCheck

SidebarAction  [Arguments]    ${type}    ${id}
    ClickElement   xpath=//div[contains(@class,'oe_view_manager_sidebar')]/div[not(contains(@style,'display: none'))]//div[contains(@class,'oe_sidebar')]//div[contains(@class,'oe_form_dropdown_section') and descendant::a[@data-bt-type='${type}' and @data-bt-id='${id}']]/button[contains(@class,'oe_dropdown_toggle')]
    ClickLink   xpath=//div[contains(@class,'oe_view_manager_sidebar')]/div[not(contains(@style,'display: none'))]//div[contains(@class,'oe_sidebar')]//a[@data-bt-type='${type}' and @data-bt-id='${id}']
    ElementPostCheck

MainWindowButton            [Arguments]     ${button_text}
    Click Button            xpath=//td[@class='oe_application']//div[contains(@class,'oe_view_manager_current')]//button[contains(text(), '${button_text}')]
    ElementPostCheck

MainWindowNormalField       [Arguments]     ${field}    ${value}
    Input Text              xpath=//td[contains(@class, 'view-manager-main-content')]//input[@name='${field}']  ${value}
    ElementPostCheck

MainWindowSearchTextField   [Arguments]     ${field}    ${value}
    Input Text              xpath=//div[@id='oe_app']//div[contains(@id, '_search')]//input[@name='${field}']   ${value}
    ElementPostCheck

MainWindowSearchNow
    
MainWindowMany2One          [Arguments]     ${field}    ${value}
    Click Element           xpath=//td[contains(@class, 'view-manager-main-content')]//input[@name='${field}']  don't wait
    Input Text              xpath=//td[contains(@class, 'view-manager-main-content')]//input[@name='${field}']      ${value}
    Click Element           xpath=//td[contains(@class, 'view-manager-main-content')]//input[@name='${field}']/following-sibling::span[contains(@class, 'oe-m2o-drop-down-button')]/img don't wait
    Click Link              xpath=//ul[contains(@class, 'ui-autocomplete') and not(contains(@style, 'display: none'))]//a[self::*/text()='${value}']    don't wait
    ElementPostCheck
    
new date        [Arguments]    ${model}    ${field}     ${day}   ${month}    ${year}
    Click Element        xpath=//div[contains(@class,'openerp')][last()]//img[ancestor::span[descendant::input[@data-bt-testing-model_name='${model}' and @data-bt-testing-name='${field}']] and @class="oe_input_icon oe_datepicker_trigger"]
    ${month}=   Evaluate        str(${month}-${1})
    select from list by value       //select[@class="ui-datepicker-month"]  ${month}
    select from list by value       //select[@class="ui-datepicker-year"]  ${year}
    click element           //table[@class="ui-datepicker-calendar"]//a[.='${day}']
    ElementPostCheck

**demo_8_0_full_workflow.robot**

*** Settings ***

Documentation  Full workflow demonstration
Resource	odoo_8_0.robot
            
*** Test Cases ***
Valid Login
	Login	

Create User
    Char    res.partner     name    chaitanya

I have added my odoo_8_0.robot and demo_8_0_full_workflow.robot files 

**Run process :**

pybot demo_8_0_full_workflow.robot

**Occurred Error With Terminal Traceback : -**

user1@user1:~/Music/RB_AUTO_TEST/odoo-robot-framework$ pybot demo_8_0_full_workflow.robot
[ ERROR ] Error in file '/home/user1/Music/RB_AUTO_TEST/odoo-robot-framework/odoo_8_0.robot': Non-existing setting 'Library.........Selenium2Library.........run_on_failure=Selenium2Library.Capture Page Screenshot'.
==============================================================================
Demo 8 0 Full Workflow :: Full workflow demonstration                         
==============================================================================
Valid Login                                                           | PASS |
------------------------------------------------------------------------------
Create User                                                           | FAIL |
No keyword with name 'Execute Javascript' found.
------------------------------------------------------------------------------
Demo 8 0 Full Workflow :: Full workflow demonstration                 | FAIL |
2 critical tests, 1 passed, 1 failed
2 tests total, 1 passed, 1 failed
==============================================================================
Output:  /home/user1/Music/RB_AUTO_TEST/odoo-robot-framework/output.xml
Log:     /home/user1/Music/RB_AUTO_TEST/odoo-robot-framework/log.html
Report:  /home/user1/Music/RB_AUTO_TEST/odoo-robot-framework/report.html

please check and update me

**Comment by ghost** [comment] 2017-04-05 09:40
You are writing Library.........Selenium2Library.........run_on_failure=Selenium2Library.Capture Page Screenshot and you should replace the dots for spaces like in the next image:
![import](https://cloud.githubusercontent.com/assets/16671237/24699540/97607974-19f4-11e7-9c5e-ab702eff5ecf.png)

**Comment by cdasadiya** [comment] 2017-04-05 10:19
After replacing again I got the same issue hear  

[ ERROR ] Error in file '/home/user1/Music/RB_AUTO_TEST/odoo-robot-framework/odoo_8_0.robot': Non-existing setting 'Library.........Selenium2Library.........run_on_failure=Selenium2Library.Capture Page Screenshot'.

**Comment by ghost** [comment] 2017-04-05 10:40
In your error message you still have the dots, that means that you did not replace them in your test with spaces.
It should be like in the image I showed you before.

**Comment by cdasadiya** [comment] 2017-04-05 10:43
ohh sorry sorry let me do the same things again now it fixed but I found the another warning message some things like 

[ WARN ] Keyword 'Selenium2Library.Capture Page Screenshot' could not be run on failure: No browser is open
do we need to require any other configuration ?

**Comment by ghost** [comment] 2017-04-05 13:34
It is because when your test fails, you do not have a browser open. So that depends on your test.

I don't know but maybe you can solve it with:
Library    Selenium2Library       run_on_failure=Appium.Capture Page Screenshot
or:
Library     Selenium2Library       run_on_failure=Nothing

**Comment by ghost** [comment] 2017-04-18 10:58
There are no comments any more, because of that, I close the issue.

**Closed as completed by ghost** 2017-04-18 10:58 UTC
